//nova categoria
POST http://localhost:5000/categoria HTTP/1.1
Content-Type: application/json

{
    "nome_categoria": "Construção" 
}
###

//novo produto
POST http://localhost:5000/produto HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIzLCJpYXQiOjE3MDE2NTI3NDQsImV4cCI6MTcwMTY1MzA0NH0.qeMN9RKtP3hiIaYe6Im_uiPOIq8H7mlun-owjkP6KP0

{
    "nome_produto": "Aço", 
    "qtde_produto": 3,
    "id_categoria": 1  
}
###

//novo pedido
POST http://localhost:5000/pedido HTTP/1.1
Content-Type: application/json

{
    "cod_produto": 3,
    "qtde_pedido": 9
}
###

//get produtos geral
GET http://localhost:5000/produto HTTP/1.1
Content-Type: application/json
###

//get produtos por categoria
GET http://localhost:5000/produto/por-categoria/1 HTTP/1.1
###

//get produtos por quantidade
GET http://localhost:5000/produto/por-quantidade-pedido/3 HTTP/1.1
Content-Type: application/json
###

//login
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
  "email": "usuario@teste.com",
  "senha": "senha123"
}

